---

- name: Create a problem server
  hosts: problemservers
  become: yes
  become_user: root
  remote_user: root
  roles:
    - common
    - problems
  tasks:
    - name: add docker key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
        state: present
      tags: packages
    - name: add docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
      tags: packages
    - name: install docker
      apt: name=docker-ce update_cache=yes state=installed
      tags: packages
    - name: setup docker services
      shell: pipenv run python3 problems/__main__.py docker --all ../problems chdir=/root/deploy
      tags: deploy
